- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: ~.*master
  become: yes
  become_method: sudo
  roles:
    - master

- hosts: ~.*node.
  become: yes
  become_method: sudo
  roles:
    - nodes

