- name: Ensure net.bridge.bridge-nf-call-iptables is set. See kubeadm
  copy: src=nomad.hcl owner=root group=root dest=/etc/nomad.d/nomad.hcl

- name: set up consul server bootstrap
  lineinfile: dest=/etc/consul.d/consul.hcl regexp="^#bootstrap_expect=" line="bootstrap_expect=1" state=present

- name: set up consul server
  lineinfile: dest=/etc/consul.d/consul.hcl regexp="^#server" line="server = true" state=present

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nomad
    - consul
